### PR TITLE
Added counting and insertion sort in additional algos file

### PR DESCRIPTION
**Pull request by drishtipeshwani**

### CODE REVIEW

**Comment by hardikhere** [comment]
insertion sort is already there, just resolve conflicts by deleting :) thanks for contribution

**Comment by drishtipeshwani** [comment]
Should i commit merge after deleting the file

**Comment by hardikhere** [comment]
> Should i commit merge after deleting the file

try taking pull from master then you will notice conficts, you can resolve easily then

**Comment by drishtipeshwani** [comment]
Thankyou ! Resolved , please merge it .

**Pull request merged**
