### PR TITLE
Rabin Karp Algorithm Added

### PR DESCRIPTION
**Pull request by Blastoise**

### CODE REVIEW

**Comment by hardikhere** [comment]
> _No description provided._

Thanks, just a little more, can you add it in a folder with topic name on which this algo is based on. please! :)

**Comment by Blastoise** [comment]
I have already done that. It's added in a folder named String Algorithm.

**Comment by hardikhere** [comment]
> I have already done that. It's added in a folder named String Algorithm.

ohk Thanks a lot I will merge that soon Thanks :)

**Comment by Blastoise** [comment]
Great :).

**Pull request merged**
